server:
  port: 8888

spring:
  security:
    user:
      name: supconit
      password: supconit
  devtools:
    livereload:
      enabled: true
      port: 6523
    restart:
      additional-exclude:
      additional-paths:
      enabled: true

